### ISSUE TITLE
[feat]: Translation Support?

### ISSUE THREAD

**Issue by ghost** [NotZer0Two/NotAnAPI#3]
Hello!

Something which could be implemented at some point in the future is translation support for strings. This can be a setting which you can add to any constructor and, if a generic translation is included, it can use a natively support language or use a default.

For example, you can create a abstract translation class.

```cs
public abstract class Translation
{
    public virtual string English { get; set; }
    public virtual string Spanish { get; set; }
}
```

Then, your text storage class can be something like:

```cs
public class MyButtonText : TranslationBase
{
    public override string English { get; set; } = "My Text";
    // No Spanish translation provided, use English as default.
}
```

Then the supported language can be used and, if not, English can be used as default.

This is a suggestion which can be ignored if you believe it to be too difficult, but translation support would be a neat feature to include as a feature.

Thanks,
Alex.

**Comment by NotZer0Two** [comment]
Translation support is already here with the class Translation but i don't like see this useful other than being cache

**Comment by ghost** [comment]
Closing due to being stale.
